spring:
  application:
    name: springboot-api-gateway
  cloud:
    gateway:
      routes:
      - id: users-status-check
        uri: http://localhost:8081
        predicates:
        - Path=/apigateway/users/status/check
        - Method=GET
        filters:
        - RemoveRequestHeader=Cookie
server:
  port: 8082

logging:
  level:
    org:
      springframework: debug
