spring:
  application:
    name: springboot-photos-resourceserver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/appsdeveloperrealm/protocol/openid-connect/certs
server:
  port: 8090

logging:
  level:
    org:
      springframework: debug
